// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/teleghost.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PacketType определяет тип пакета
type PacketType int32

const (
	PacketType_PACKET_TYPE_UNSPECIFIED PacketType = 0
	PacketType_HEARTBEAT               PacketType = 1 // Keep-alive сигнал
	PacketType_TEXT_MESSAGE            PacketType = 2 // Текстовое сообщение
	PacketType_PROFILE_UPDATE          PacketType = 3 // Обновление профиля
	PacketType_HANDSHAKE               PacketType = 4 // Рукопожатие для установки соединения
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "PACKET_TYPE_UNSPECIFIED",
		1: "HEARTBEAT",
		2: "TEXT_MESSAGE",
		3: "PROFILE_UPDATE",
		4: "HANDSHAKE",
	}
	PacketType_value = map[string]int32{
		"PACKET_TYPE_UNSPECIFIED": 0,
		"HEARTBEAT":               1,
		"TEXT_MESSAGE":            2,
		"PROFILE_UPDATE":          3,
		"HANDSHAKE":               4,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_teleghost_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_proto_teleghost_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{0}
}

// Packet — универсальная обёртка для всех сообщений в сети
type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Версия протокола для обратной совместимости
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Тип содержимого пакета
	Type PacketType `protobuf:"varint,2,opt,name=type,proto3,enum=teleghost.PacketType" json:"type,omitempty"`
	// Публичный ключ отправителя (Ed25519, 32 bytes)
	SenderPubKey []byte `protobuf:"bytes,3,opt,name=sender_pub_key,json=senderPubKey,proto3" json:"sender_pub_key,omitempty"`
	// Подпись payload (Ed25519 signature, 64 bytes)
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Зашифрованное/сериализованное содержимое (в зависимости от type)
	Payload       []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_proto_teleghost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Packet) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_PACKET_TYPE_UNSPECIFIED
}

func (x *Packet) GetSenderPubKey() []byte {
	if x != nil {
		return x.SenderPubKey
	}
	return nil
}

func (x *Packet) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Packet) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// TextMessage — текстовое сообщение в чате
type TextMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный ID чата (обычно hash публичных ключей обоих участников)
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Содержимое сообщения (UTF-8)
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Unix timestamp в миллисекундах
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Уникальный ID сообщения (UUID)
	MessageId     string `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMessage) Reset() {
	*x = TextMessage{}
	mi := &file_proto_teleghost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMessage) ProtoMessage() {}

func (x *TextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMessage.ProtoReflect.Descriptor instead.
func (*TextMessage) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{1}
}

func (x *TextMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *TextMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TextMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// ProfileUpdate — обновление профиля пользователя
type ProfileUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Никнейм пользователя (max 64 символа)
	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Описание/био (max 256 символов)
	Bio string `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	// Аватар (сжатое изображение, max 64KB, WebP/JPEG)
	Avatar        []byte `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdate) Reset() {
	*x = ProfileUpdate{}
	mi := &file_proto_teleghost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdate) ProtoMessage() {}

func (x *ProfileUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdate.ProtoReflect.Descriptor instead.
func (*ProfileUpdate) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileUpdate) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileUpdate) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ProfileUpdate) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

// Handshake — начало сессии между двумя пирами
type Handshake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Публичный ключ инициатора
	InitiatorPubKey []byte `protobuf:"bytes,1,opt,name=initiator_pub_key,json=initiatorPubKey,proto3" json:"initiator_pub_key,omitempty"`
	// Временный ключ для ECDH (X25519)
	EphemeralPubKey []byte `protobuf:"bytes,2,opt,name=ephemeral_pub_key,json=ephemeralPubKey,proto3" json:"ephemeral_pub_key,omitempty"`
	// Nonce для предотвращения replay атак
	Nonce []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Timestamp для проверки свежести
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_proto_teleghost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{3}
}

func (x *Handshake) GetInitiatorPubKey() []byte {
	if x != nil {
		return x.InitiatorPubKey
	}
	return nil
}

func (x *Handshake) GetEphemeralPubKey() []byte {
	if x != nil {
		return x.EphemeralPubKey
	}
	return nil
}

func (x *Handshake) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Handshake) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_teleghost_proto protoreflect.FileDescriptor

const file_proto_teleghost_proto_rawDesc = "" +
	"\n" +
	"\x15proto/teleghost.proto\x12\tteleghost\"\xab\x01\n" +
	"\x06Packet\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.teleghost.PacketTypeR\x04type\x12$\n" +
	"\x0esender_pub_key\x18\x03 \x01(\fR\fsenderPubKey\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"}\n" +
	"\vTextMessage\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\"U\n" +
	"\rProfileUpdate\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\fR\x06avatar\"\x97\x01\n" +
	"\tHandshake\x12*\n" +
	"\x11initiator_pub_key\x18\x01 \x01(\fR\x0finitiatorPubKey\x12*\n" +
	"\x11ephemeral_pub_key\x18\x02 \x01(\fR\x0fephemeralPubKey\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp*m\n" +
	"\n" +
	"PacketType\x12\x1b\n" +
	"\x17PACKET_TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tHEARTBEAT\x10\x01\x12\x10\n" +
	"\fTEXT_MESSAGE\x10\x02\x12\x12\n" +
	"\x0ePROFILE_UPDATE\x10\x03\x12\r\n" +
	"\tHANDSHAKE\x10\x04B+Z)github.com/teleghost/internal/proto;protob\x06proto3"

var (
	file_proto_teleghost_proto_rawDescOnce sync.Once
	file_proto_teleghost_proto_rawDescData []byte
)

func file_proto_teleghost_proto_rawDescGZIP() []byte {
	file_proto_teleghost_proto_rawDescOnce.Do(func() {
		file_proto_teleghost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_teleghost_proto_rawDesc), len(file_proto_teleghost_proto_rawDesc)))
	})
	return file_proto_teleghost_proto_rawDescData
}

var file_proto_teleghost_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_teleghost_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_teleghost_proto_goTypes = []any{
	(PacketType)(0),       // 0: teleghost.PacketType
	(*Packet)(nil),        // 1: teleghost.Packet
	(*TextMessage)(nil),   // 2: teleghost.TextMessage
	(*ProfileUpdate)(nil), // 3: teleghost.ProfileUpdate
	(*Handshake)(nil),     // 4: teleghost.Handshake
}
var file_proto_teleghost_proto_depIdxs = []int32{
	0, // 0: teleghost.Packet.type:type_name -> teleghost.PacketType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_teleghost_proto_init() }
func file_proto_teleghost_proto_init() {
	if File_proto_teleghost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_teleghost_proto_rawDesc), len(file_proto_teleghost_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_teleghost_proto_goTypes,
		DependencyIndexes: file_proto_teleghost_proto_depIdxs,
		EnumInfos:         file_proto_teleghost_proto_enumTypes,
		MessageInfos:      file_proto_teleghost_proto_msgTypes,
	}.Build()
	File_proto_teleghost_proto = out.File
	file_proto_teleghost_proto_goTypes = nil
	file_proto_teleghost_proto_depIdxs = nil
}
