linters:
  enable:
    - gosec
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  gosec:
    excludes:
      - G104 # Unhandled errors - слишком шумно для Close/Remove
      - G304 # File inclusion via variable - необходимо для работы с динамическими путями в приложении
      - G115 # Integer overflow - мы будем фиксить их точечно, где это реально опасно
      - G103 # Unsafe calls - протево protobuf использует unsafe, это нормально

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
